### ISSUE TITLE
Vyhnutí se is_err - unwrap

### ISSUE THREAD

**Issue by DolajoCZ** [bennySim/tictactoe#1]
https://github.com/bennySim/tictactoe/blob/3e06cffc8f3b437a07b4393b5dc5768309cec194/src/main.rs#L396-L403

Tento blok kódu bych navrhoval nahradit tímto. Tato implementace má výhodu, že nepoužívá `unwrap` a není tedy závislá na předchozí kontrole `is_err()`

```rust
    match (x, y) {
        (Ok(x), Ok(y)) => convert_coords(x, y).ok_or(CoordinatesError::InvalidValue),
        (_, _) => Err(CoordinatesError::InvalidFormat)
    }
```

**Comment by bennySim** [comment]
Velmi pekne zjednodusenie, fakt diki!
