### ISSUE TITLE
Return from match

### ISSUE THREAD

**Issue by DolajoCZ** [bennySim/tictactoe#3]
https://github.com/bennySim/tictactoe/blob/3e06cffc8f3b437a07b4393b5dc5768309cec194/src/main.rs#L422-L433

Uvedený zápis je možné následně zjednodušit

```
    let x= match x {
        'A' => 0,
        'B' => 1,
        'C' => 2,
        _ => return None,
    };

    match (1..=3).contains(&y)  {
        true => Some((x, (y-1) as usize)),
        false => None
    }
```

**Comment by bennySim** [comment]
Tým pádom netreba v match vracat option

**Comment by bennySim** [comment]
Prva cast opravena, ale s matchom nesuhlasim, pride mi, ze presne na tieto ucely je if-then-else
